Repository projen/canary-testing, pull requests merged in 2024-07, with the labels that each got.

#7 chore(deps): upgrade dependencies
  .projen/tasks.json
  package.json
  yarn.lock
Labels: auto-approve

#9 chore: extend readme
  README.md
Labels: documentation

#10 chore: update readme
  README.md
Labels: backport-to-v1

#15 chore: fix condition
  .github/workflows/backport.yml
  .projenrc.ts
Labels: documentation

#12 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve
